version: '3'
services:
  genca:
    image: genca:latest
    build:
      context: .
      dockerfile: ./docker/genca/Dockerfile
  kldb:
    image: kldb:latest
    build:
      context: .
      dockerfile: ./docker/kldb/Dockerfile
    ports:
    - "27017:27017"
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=foo
    - MONGO_INITDB_DATABASE=dev
  klapi:
    image: klapi:latest
    build:
      context: .
      dockerfile: ./docker/klapi/Dockerfile
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    environment:
    - MONGODB_URI=mongodb://kl:foo@kldb:27017/dev
    - NODE_ENV=development
    depends_on:
    - genca
    - kldb
    restart: on-failure
